M48
; DRILL file {KiCad 7.0.6} date Mon Sep  4 15:45:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-04T15:45:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X2.8Y42.4
X2.8Y35.6
X3.9Y71.8
X9.9Y71.8
X124.0Y67.4
X124.0Y52.4
X130.0Y67.4
X130.0Y52.4
T0
M30
