/* GENERATED by tulip/shared/gen_amy_kwmap.py -- do not edit.
 * Source of truth: amy/amy/__init__.py _KW_MAP_LIST at d97d230ba590
 * (64 keywords). Regenerate whenever the amy pin moves; the
 * amy-pin-check workflow enforces freshness with --check.
 *
 * Index in this table is the keyword's PRIORITY: _KW_MAP_LIST is
 * ordered, and patch_string must come last on the wire. */

/* Names, not MP_QSTR_ constants: referencing those from a table like
 * this makes MicroPython's qstr extractor emit them alongside the
 * frozen modules' own pool and the build fails on redeclared
 * enumerators. The C side interns them once with qstr_find_strn()
 * instead, which also means a keyword no frozen module ever mentions
 * simply never matches -- and never matching is a bail to Python,
 * which is the safe direction. */
typedef struct {
    const char *name;    /* the Python keyword */
    const char *wire;    /* wire prefix, one or two chars */
    char        type;    /* I int, F float, S str, L list, C coefs */
} amy_kw_t;

static const amy_kw_t AMY_KW[] = {
    {"ticks", "H", 'L'},
    {"osc", "v", 'I'},
    {"wave", "w", 'I'},
    {"note", "n", 'F'},
    {"vel", "l", 'F'},
    {"amp", "a", 'C'},
    {"freq", "f", 'C'},
    {"duty", "d", 'C'},
    {"feedback", "b", 'F'},
    {"reset", "S", 'I'},
    {"phase", "P", 'F'},
    {"pan", "Q", 'C'},
    {"client", "g", 'I'},
    {"volume", "V", 'F'},
    {"pitch_bend", "s", 'F'},
    {"filter_freq", "F", 'C'},
    {"resonance", "R", 'F'},
    {"bp0", "A", 'L'},
    {"bp1", "B", 'L'},
    {"eg0", "A", 'L'},
    {"eg1", "B", 'L'},
    {"eg0_type", "T", 'I'},
    {"eg1_type", "X", 'I'},
    {"debug", "D", 'I'},
    {"chained_osc", "c", 'I'},
    {"mod_source", "L", 'L'},
    {"eq", "x", 'L'},
    {"filter_type", "G", 'I'},
    {"ratio", "I", 'F'},
    {"latency_ms", "N", 'I'},
    {"algo_source", "O", 'L'},
    {"load_sample", "z", 'L'},
    {"transfer_file", "zT", 'L'},
    {"disk_sample", "zF", 'L'},
    {"algorithm", "o", 'I'},
    {"chorus", "k", 'L'},
    {"reverb", "h", 'L'},
    {"echo", "M", 'L'},
    {"patch", "K", 'I'},
    {"external_channel", "W", 'I'},
    {"portamento", "m", 'I'},
    {"tempo", "j", 'F'},
    {"sequencer_run", "zY", 'I'},
    {"external_midi_sync", "zC", 'I'},
    {"synth", "i", 'I'},
    {"pedal", "ip", 'I'},
    {"synth_flags", "if", 'I'},
    {"num_voices", "iv", 'I'},
    {"oscs_per_voice", "in", 'I'},
    {"synth_level", "iV", 'F'},
    {"to_synth", "it", 'I'},
    {"grab_midi_notes", "im", 'I'},
    {"note_source_channel", "iM", 'I'},
    {"synth_delay", "id", 'I'},
    {"preset", "p", 'I'},
    {"num_partials", "p", 'I'},
    {"start_sample", "zS", 'L'},
    {"stop_sample", "zO", 'I'},
    {"bus", "y", 'I'},
    {"mode", "ww", 'I'},
    {"midi_cc", "ic", 'L'},
    {"midi_note_cmd", "io", 'L'},
    {"cv_trigger", "ig", 'L'},
    {"patch_string", "u", 'S'},
};
#define AMY_KW_N 64
