#!/usr/bin/env python3
"""Regenerate ``amy_kwmap.h``, the C copy of AMY's keyword map.

``tulip.amy_message()`` (amy_connector.c) is ``amy.message()`` rewritten in C,
and this table is what it walks: one row per keyword in ``_KW_MAP_LIST`` from
``amy/amy/__init__.py``. That list is AMY's source of truth — the JS and
GDScript bindings are generated from it too — so this C copy is GENERATED
rather than hand-written: a hand-copied fourth version would drift the first
time a keyword was added.

The output is a **committed** file, like ``tulip/server/refdocs/amy/``, because
the header is needed by every firmware/web/desktop build and none of those
build systems should each grow a codegen step. The ``amy-pin-check`` workflow
runs ``--check`` on any PR that moves the amy pin, so it cannot go stale.

The list is sourced from the **pinned** amy commit (the gitlink recorded in
this repo), preferring the local submodule when it is checked out at the pin
and falling back to GitHub raw otherwise (CI has no submodule checkout). It is
read with ``ast.literal_eval`` rather than by importing amy, which would drag
in amy's whole C-API resolution at import time.

Usage:
    python3 tulip/shared/gen_amy_kwmap.py             # regenerate the header
    python3 tulip/shared/gen_amy_kwmap.py --check     # exit 1 if header is stale
"""
from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SUBMODULE_INIT = REPO_ROOT / "amy" / "amy" / "__init__.py"
OUT_PATH = Path(__file__).resolve().parent / "amy_kwmap.h"
RAW_URL = "https://raw.githubusercontent.com/shorepine/amy/{sha}/amy/__init__.py"


def pinned_sha() -> str:
    """The amy commit this repo's gitlink points at (``160000 commit <sha>\tamy``)."""
    out = subprocess.check_output(
        ["git", "-C", str(REPO_ROOT), "ls-tree", "HEAD", "amy"], text=True
    )
    return out.split()[2]


def submodule_head() -> str | None:
    """The commit the amy submodule working tree is actually checked out at."""
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO_ROOT / "amy"), "rev-parse", "HEAD"],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def amy_init_source(sha: str) -> str:
    """amy/__init__.py at the pinned SHA: local submodule if it sits at the
    pin (so a submodule on some other commit can't silently feed the table),
    else GitHub raw."""
    if SUBMODULE_INIT.is_file() and submodule_head() == sha:
        return SUBMODULE_INIT.read_text()
    with urllib.request.urlopen(RAW_URL.format(sha=sha)) as resp:
        return resp.read().decode("utf-8")


def kw_map_list(src: str) -> list[tuple[str, str]]:
    m = re.search(r"^_KW_MAP_LIST\s*=\s*(\[.*?^\])", src, re.S | re.M)
    if not m:
        raise SystemExit("could not find _KW_MAP_LIST in amy/amy/__init__.py")
    return ast.literal_eval(m.group(1))


def render(entries: list[tuple[str, str]], sha: str) -> str:
    out = []
    w = out.append
    w("/* GENERATED by tulip/shared/gen_amy_kwmap.py -- do not edit.")
    w(" * Source of truth: amy/amy/__init__.py _KW_MAP_LIST at %s" % sha[:12])
    w(" * (%d keywords). Regenerate whenever the amy pin moves; the" % len(entries))
    w(" * amy-pin-check workflow enforces freshness with --check.")
    w(" *")
    w(" * Index in this table is the keyword's PRIORITY: _KW_MAP_LIST is")
    w(" * ordered, and patch_string must come last on the wire. */")
    w("")
    w("/* Names, not MP_QSTR_ constants: referencing those from a table like")
    w(" * this makes MicroPython's qstr extractor emit them alongside the")
    w(" * frozen modules' own pool and the build fails on redeclared")
    w(" * enumerators. The C side interns them once with qstr_find_strn()")
    w(" * instead, which also means a keyword no frozen module ever mentions")
    w(" * simply never matches -- and never matching is a bail to Python,")
    w(" * which is the safe direction. */")
    w("typedef struct {")
    w("    const char *name;    /* the Python keyword */")
    w("    const char *wire;    /* wire prefix, one or two chars */")
    w("    char        type;    /* I int, F float, S str, L list, C coefs */")
    w("} amy_kw_t;")
    w("")
    w("static const amy_kw_t AMY_KW[] = {")
    for name, code in entries:
        wire, tcode = code[:-1], code[-1]
        w('    {"%s", "%s", \'%s\'},' % (name, wire, tcode))
    w("};")
    w("#define AMY_KW_N %d" % len(entries))
    w("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed header is stale")
    ap.add_argument("--sha", help="generate from this amy SHA, not the gitlink")
    args = ap.parse_args()

    sha = args.sha or pinned_sha()
    want = render(kw_map_list(amy_init_source(sha)), sha)

    if args.check:
        have = OUT_PATH.read_text() if OUT_PATH.is_file() else ""
        # Compare everything below the header comment (which carries the
        # SHA): a pin bump that doesn't change _KW_MAP_LIST should not
        # count as stale, or every amy bump would demand a no-op commit.
        strip = lambda s: s[s.index("typedef"):] if "typedef" in s else s
        if strip(have) != strip(want):
            print("STALE: %s does not match _KW_MAP_LIST at amy %s" %
                  (OUT_PATH.relative_to(REPO_ROOT), sha[:12]))
            print("Run: python3 tulip/shared/gen_amy_kwmap.py  (then commit)")
            return 1
        print("OK: amy_kwmap.h matches _KW_MAP_LIST at amy %s" % sha[:12])
        return 0

    OUT_PATH.write_text(want)
    print("wrote %s (%s)" % (OUT_PATH.relative_to(REPO_ROOT), sha[:12]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
