#include "py/builtin.h"

const char tulip_esp32_help_text[] =
    "Welcome to Tulip!\n"
    "\n"
    "For more information online please visit https://tulip.computer/\n"
    "\n"
    "Try help(tulip) or help(alles) to see how to control the screen and synthesizer\n"
    "\n"
    "tulip.wifi('ssid', 'password') joins a WiFi network\n"
    "\n"
    "tulip.edit('filename.py') opens the editor. Use control-X to quit.\n"
    "\n"
    "Control commands:\n"
    "  CTRL-C        -- interrupt a running program\n"
    "  CTRL-D        -- on a blank line, do a soft reset\n"
    "\n"
    "For further help on a specific object, type help(obj)\n"
    "For a list of available modules, type help('modules')\n"
;

const char tulip_desktop_help_text[] =
    "Welcome to Tulip!\n"
    "\n"
    "For more information online please visit https://tulip.computer/\n"
    "\n"
    "Try help(tulip) or help(alles) to see how to control the screen and synthesizer\n"
    "\n"
    "tulip.edit('filename.py') opens the editor. Use control-X to quit.\n"
    "\n"
    "Control commands:\n"
    "  CTRL-C        -- interrupt a running program\n"
    "\n"
    "For further help on a specific object, type help(obj)\n"
    "For a list of available modules, type help('modules')\n"
;