#ifndef __TDECK_KEYBOARD_H__
#define __TDECK_KEYBOARD_H__

#include "keyscan.h"
#include "tulip_helpers.h"
#include "esp_timer.h"


#define TDECK_POWERON       10
#define TDECK_I2C_SDA       18
#define TDECK_I2C_SCL       8
#define LILYGO_KB_SLAVE_ADDRESS     0x55
#define TDECK_TOUCH_ADDR_0 0x14
#define TDECK_TOUCH_ADDR_1 0x5D

#define TDECK_TRACKBALL_UP 3
#define TDECK_TRACKBALL_DOWN 15
#define TDECK_TRACKBALL_LEFT 1
#define TDECK_TRACKBALL_RIGHT 2
#define TDECK_TRACKBALL_CLICK 0

#define TDECK_TOUCH_INT 16

#define SHIFT_MICROPHONE 224
#define TDECK_UP_KEY 259
#define TDECK_DOWN_KEY 258
#define TDECK_LEFT_KEY 260
#define TDECK_RIGHT_KEY 261
#define DEVICE_CONTROL_1 17
#define END_OF_TRANSMISSION_BLOCK 23
#define ENQUIRY_CHARACTER 5
#define DEVICE_CONTROL_2 18
#define DEVICE_CONTROL_4 20
#define END_OF_MEDIUM 25
#define NEGATIVE_ACKNOWLEDGE_CHARACTER 21
#define HORIZONTAL_TAB 9
#define SHIFT_IN 15
#define DATA_LINK_ESCAPE 16
#define START_OF_HEADING 1
#define DEVICE_CONTROL_3 19
#define END_OF_TRANSMISSION_CHARACTER 4
#define ACKNOWLEDGE_CHARACTER 6
#define BELL_CHARACTER 7
#define BACKSPACE_CHARACTER 8
#define LINEFEED_CHARACTER 10
#define VERTICAL_TAB 11
#define FORMFEED 12
#define SUBSTITUTE_CHARACTER 26
#define CANCEL_CHARACTER 24
#define END_OF_TEXT_CHARACTER 3
#define SYNCHRONOUS_IDLE 22
#define START_OF_TEXT 2
#define SHIFT_OUT 14
#define CARRIAGE_RETURN 13
#define DELETE_CHARACTER 127
#define ESCAPE_CHARACTER 27

// How long you hold down a key before it starts repeating
#define KEY_REPEAT_TRIGGER_MS 500
// How often (in ms) to repeat a key once held
#define KEY_REPEAT_INTER_MS 90

void run_tdeck_keyboard();

#endif
